# Generated by Django 4.2.2 on 2023-06-30 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_remove_question_section_form_is_draft_subsection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subsection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='formapp.subsection'),
        ),
    ]
