# Generated by Django 4.2.2 on 2023-07-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_alter_question_subsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='formassignment',
            name='responses',
            field=models.ManyToManyField(to='formapp.response'),
        ),
        migrations.AddField(
            model_name='response',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
