# Generated by Django 4.2.2 on 2023-07-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_formassignment_responses_response_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='formassignment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
