# Generated by Django 4.2.2 on 2023-07-03 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0006_alter_question_subsection_alter_section_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formassignment',
            name='completed',
        ),
        migrations.AlterField(
            model_name='question',
            name='subsection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='formapp.subsection'),
        ),
        migrations.AlterField(
            model_name='section',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.form'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.section'),
        ),
    ]
