# Generated by Django 4.2.2 on 2023-07-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0007_remove_formassignment_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formassignment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
