# Generated by Django 4.2.2 on 2023-07-03 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0009_alter_question_subsection_alter_section_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formassignment',
            name='completed',
        ),
    ]
