# Generated by Django 4.2.2 on 2023-07-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0014_remove_form_total_score_remove_section_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formassignment',
            name='total_score',
        ),
        migrations.AddField(
            model_name='form',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='section',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subsection',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
